name: Reactjs CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: yarn

      - name: Test and coverage
        run: yarn vitest --coverage

      #Exécuter le build de l'application
      - name: Build the application
        run: npm run build || true

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}} # URL pour le serveur SonarQube/SonarCloud
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

      #Afficher un message de confirmation
      - name: Confirm Build Success
        run: echo "Build completed successfully!"